/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQU1PWm5JMlBQMGFkbGlQSkhDM1JndmZoUWxBcFhoZEVaL3duSlBkV0tHdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicU9SWXhJRlJlK0pCQ1lkTCsxeTE1akdlWk8vb0g3ZE9MeXMxdGdvd3duUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1SnJiQmJQRXFXV05ua1JKOXB5SkM5emlqcHY0TEwxcmZrRHltdHB1Nm13PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJQeC9DdjBSV1B4Z1EzczVOcjNoR0dmRG9TV0U0Q0s4blp2ekVVOXdDQ1hRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1GWGpPNzJmUlRhYVpRWWFUR2FKdHB0N3JmR1NuRFJkL0ZWblB2dWh1RzQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJMd0c1bmNjakpKRlVJNThqNEo1WmhyUnhHTGJsN3ZJS1RzQy8vSlBiaXM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkxQMnd2MmRXd2I3WGxKTmwxdHdpM09tUlViZjhDUjhDdVh6b0E3R2QzUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUWs4K1pVY1E2Uk1QNTBpU1ZZOTZsNFE0MWVNS3QwMmN6SytmZlFYTWtXQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjV5SU16N3QwTnp3c3ZNWFRIVUVuUW5uVTk4clkvOVd6TVROaXNWTi96WnE0TDd5bVJkWmN2WnFDRzZPYTJjdFc2S25PZkV2dm01Ry9yQTBhZUhFdGlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjE1LCJhZHZTZWNyZXRLZXkiOiIvWXEwNEZucUxVU1dBOW14N1NzT2gvSlpYZWNNdzhuUHdVWnpzK1Z1ays4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJCSVdqbXVTalE0U2ZneElSNlQ5aGxRIiwicGhvbmVJZCI6IjU0ODI0MTk2LTI4MmEtNDQ1Zi04MjUwLWY0MGExNzE1NDBhMSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJSQUM2RytBREh4RU9xT3hMYlVTMXlDNFU4WjQ9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaGZmR0x3dnN5eXZ2NW92NWFEbmpHWGw5S3ZNPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6Ik02QzQ0ODE2IiwibWUiOnsiaWQiOiIyNTQ3MjQyNjU0NDQ6NjhAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ051SHVkNEJFTStLM0xrR0dBMGdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjhYYVZyRmVXVWI0QmYvMWc2NERTenZqQTlYM0g4bXpFWERwWklsc3ZVajg9IiwiYWNjb3VudFNpZ25hdHVyZSI6IktGWXpaYjlDSjNRS04zT2liU25BQTl5eWQ0YSt2ZFE5WU5TejBUM29qWFBqeCs1MVRJQ2xyQ21LSXNpT1lLdHdBQ3VMMDNrcnJjUlh6YnlGdE1Ob0F3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJMTkdDaWUrUmkrWlhxZExVbksrWFVobEV6TmR0Y2N6OWhoV255Y3hwK2pXOWlwdWVncGlxTW5ENXNVZU9aQk56SlQ2QldGWkh2QmJWeHZtaGJHRjFpZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDcyNDI2NTQ0NDo2OEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJmRjJsYXhYbGxHK0FYLzlZT3VBMHM3NHdQVjl4L0pzeEZ3NldTSmJMMUkvIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMxNjU5MTA3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUdqRyJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾-𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
